// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ51viAmLcAElhQo6rMM3oVuMpntsqSJI',
    appId: '1:935257598974:web:3208980f3402e309af6eaf',
    messagingSenderId: '935257598974',
    projectId: 'insta-c9327',
    authDomain: 'insta-c9327.firebaseapp.com',
    storageBucket: 'insta-c9327.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjybYtaAG8vkA-Vu3Plx5i08tml_Fjg8k',
    appId: '1:935257598974:android:fa92fa7cd7eb2e94af6eaf',
    messagingSenderId: '935257598974',
    projectId: 'insta-c9327',
    storageBucket: 'insta-c9327.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKx3JZiZDG6hisNObaOC-Wnt1SQxU-ZSQ',
    appId: '1:935257598974:ios:8889da71fe39e3a3af6eaf',
    messagingSenderId: '935257598974',
    projectId: 'insta-c9327',
    storageBucket: 'insta-c9327.appspot.com',
    iosBundleId: 'com.example.insta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKx3JZiZDG6hisNObaOC-Wnt1SQxU-ZSQ',
    appId: '1:935257598974:ios:728e5b6616579177af6eaf',
    messagingSenderId: '935257598974',
    projectId: 'insta-c9327',
    storageBucket: 'insta-c9327.appspot.com',
    iosBundleId: 'com.example.insta.RunnerTests',
  );
}
